# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

    - name: Create env file
      run: |
        touch .env
        echo ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} >> .env
        echo NUMBER_ID=${{ secrets.NUMBER_ID }} >> .env
        cat .env

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
